### PR TITLE
Upgrade React to stable (15.0.1)

### PR DESCRIPTION
**Pull request by antoinerousseau**
Current issue:

```
$ npm i --save react@15

npm ERR! peerinvalid The package react@15.0.1 does not satisfy its siblings' 
peerDependencies requirements!
npm ERR! peerinvalid Peer react-dnd@2.1.4 wants react@^0.14.0 || ^15.0.0-0
```

### CODE REVIEW

**Comment by billyjanitsch** [comment]
Thanks -- can you also update the peer dependency, instead of just the dev dependencies? That's the one that's causing you trouble.

FYI, you should consider using npm@3 instead of 2 -- peer dependency errors have been replaced by warnings, so they don't block your build.

**Comment by antoinerousseau** [comment]
oops yeah sorry the peer dependency was my initial goal! fixed.

Thanks for the tip for NPM 3, didn't know!!

**Comment by billyjanitsch** [comment]
Thanks! :)

**Comment by gaearon** [comment]
Um, no, `0-0` was intentional and according to http://semver.npmjs.com/ should match both 15 RC and 15 stable.

**Comment by antoinerousseau** [comment]
Fair enough, but then why do I get `The package react@15.0.1 does not satisfy its siblings' peerDependencies requirements!` followed by `Peer react-dnd@2.1.4 wants react@^0.14.0 || ^15.0.0-0`?

But then I just realized that I was executing NPM v2.14.12, and when upgrading to NPM 3 the issue disappeared... weird.

**Comment by gaearon** [comment]
I explain the problem a little more here: https://github.com/reactjs/react-redux/pull/342#issuecomment-207647767
Basically npm@2.x has very unhelpful behavior of listing *all* packages that peer depend on something even when *just one* peer dependency actually fails. As soon as you fix the actually problematic dependency, the error will go away. But yeah, you can upgrade to npm@3.x as well.

For the record, I reverted this PR because it has an unfortunate side effect of forcing people to use >=15.0.1 whereas there is no reason why they shouldn’t be able to stay on 15RC if they want to.

**Comment by billyjanitsch** [comment]
Sorry for the mistake, @gaearon! I remember wondering whether `0-0` would actually match non-RCs -- I took this issue as confirmation that it didn't, but I should have double-checked.

**Comment by gaearon** [comment]
I get confused by this all the time so I suggest using semver.npmjs.com to double check.

**Pull request merged**
