### PR TITLE
fix selected text drop issue in Firefox #219

### PR DESCRIPTION
**Pull request by ttrmw**
Moved `e.preventDefault()` outside of the `isDraggingNativeItem` check, as the default must be prevented in Firefox for non Native items too.

Should `isFirefox` be checked here? I tested in Chrome and found no issue with preventing the default.

### CODE REVIEW

**Comment by ttrmw** [comment]
@gaearon Any movement on this? Looks like it's not quite a dupe of #242 as the default must be prevented at capture AND bubble for our separate issues

**Comment by gaearon** [comment]
Hey, sorry, I don't currently have time to review this. I might have some time in September.

As you can see from React DnD API, the backend is pluggable.
Feel free to fork HTML5 backend for now, publish it as a separate package, and use it with your fix.

**Comment by ryanhiebert** [comment]
I can confirm that this works for me. I was seeing the issue mentioned in #221, and using this patched solved the problem.

**Comment by ttrmw** [comment]
Hey @ryanhiebert, I think #221 is subtly different. @Enet4 found my patch didn't help. 

There is another PR -  #242 - which cancels Firefox's event handling at bubble. That fixed #221 for Enet4 but didn't help me with #219

**Comment by ryanhiebert** [comment]
It may be subtly different, but it did solve my case, which is what was described in #221. I found that if I dropped an avatar which was a part of my drag layer, it would open the url to the image. Using your patch, I no longer have that issue.

**Comment by gaearon** [comment]
Thank you very much for the PR. Your PR did not merge cleanly because you included the dist file—there is no need to do this in PRs. I cherry-picked your change as a different commit so I'm closing this via 2299ece.

Cheers!

**Comment by gaearon** [comment]
The fix for this issue was released in `react-dnd@1.1.8`.
Please verify that it works.

**Comment by ttrmw** [comment]
Hey @gaearon - yep, works as expected. Sorry about the updated dist & thanks for the sort-of-merge!

**Pull request closed without merging**
