### PR TITLE
IE bugfix

### PR DESCRIPTION
**Pull request by itrelease**

### CODE REVIEW

**Comment by gaearon** [comment]
Rad! I'll take a look tomorrow, too much work stuff right now :-)

**Comment by nelix** [comment]
I wish there was a way to do this without UA detection :(

**Comment by gaearon** [comment]
Can we just call it unconditionally?

**Comment by nelix** [comment]
I can do some testing on Monday

**Comment by itrelease** [comment]
@gaearon @nelix https://github.com/gaearon/react-dnd/issues/28#issuecomment-74238523

> For the drop event to fire at all, you have to cancel the defaults of **both** the **dragover** and the **dragenter** event." — http://www.quirksmode.org/blog/archives/2009/09/the_html5_drag.html

**Comment by gaearon** [comment]
Closing as duplicate

**Pull request closed without merging**
