### PR TITLE
fix memory leak

### PR DESCRIPTION
**Pull request by longlho**
@gaearon 

Our use case is that we also render React on the server side (thus shared component code), and since component monitoring got setup in `constructor`, it's creating a memory leak in our server. The change is to move it to `componentDidMount`. However, this does make 1st render not having certain dnd props, so this is up for discussion.

cc @dekusdenial

Before:
leak

After:

no leak

### CODE REVIEW

**Comment by gaearon** [comment]
We should fix the leak but I'd prefer not to change the API for the sake of it. It seems that the correct fix is to refactor `decorateHandler` so it uses some kind of “noop monitor” that returns the initial values for every question until it's initialized with a handler ID. This way we have some initial values on the first render, and subscribe after mounting.

**Comment by longlho** [comment]
kk I'll take another stab at this.

**Comment by gaearon** [comment]
There's a global monitor but it's not useful for handlers because it only answers generic questions like “are we dragging now”. Handler-specific monitors are [SourceMonitor](https://github.com/gaearon/react-dnd/blob/master/src/createSourceMonitor.js) and [TargetMonitor](https://github.com/gaearon/react-dnd/blob/master/src/createTargetMonitor.js) and they answer the questions about particular handlers (e.g. are we dragging over this target?). They are created [here](https://github.com/gaearon/react-dnd/blob/a634a9cca92524ee80beeb77e649dfdbc4b9c347/src/decorateHandler.js#L63).

Handler monitors are required for the rendering (that's what get passed to `collect` function). But currently they *have* to be initialized with handler ID! (Without an ID, they don't know which handler information to query.)

What I'm proposing essentially is to move [this call](https://github.com/gaearon/react-dnd/blob/a634a9cca92524ee80beeb77e649dfdbc4b9c347/src/decorateHandler.js#L67) to `componentDidMount`. But then `this.handlerMonitor` and `this.handlerConnector` will be undefined when `getCurrentState()` is called for filling the initial state! That's the problem. This is why I'm proposing to change them so they can be initialized later. So basically `handlerConnector` would be a no-op connector, and `handlerMonitor` will be a dummy monitor that doesn't have an ID assigned yet and answers "no" to ID-specific questions.

The only catch here is I'm not sure what to do about the initial state of a component with custom `isDragging` implementation. We want to display it as *already dragging* right when it mounts if that implementation returns `true`. Maybe we can have some sort of special case for that. Let's not worry about this initially and come back to this after other cases work.

**Comment by gaearon** [comment]
In fact `this.handlerMonitor` is [created without an explicit ID](https://github.com/gaearon/react-dnd/blob/a634a9cca92524ee80beeb77e649dfdbc4b9c347/src/decorateHandler.js#L63) and [receives it later](https://github.com/gaearon/react-dnd/blob/a634a9cca92524ee80beeb77e649dfdbc4b9c347/src/decorateHandler.js#L111) so maybe we can just tweak it to return sensible answers when ID is not specified yet (as opposed to crashing—I assume [this line](https://github.com/gaearon/react-dnd/blob/a634a9cca92524ee80beeb77e649dfdbc4b9c347/src/createTargetMonitor.js#L30) would crash for example).

**Comment by gaearon** [comment]
Any updates on this? Have you been using a fork?

**Comment by longlho** [comment]
yeah sorry I haven't got time :( we've been conditionally disabling `dnd` on the server side

**Comment by gaearon** [comment]
Can you please test my approach to this in #379?
If it works, I can try making #379 complete and releasing it.

**Comment by longlho** [comment]
yup will do :)

**Pull request closed without merging**
