### PR TITLE
Update bower package to 0.6.4

### PR DESCRIPTION
**Pull request by jgable**
I'll publish as soon as this is updated.

### CODE REVIEW

**Comment by jgable** [comment]
@gaearon Next time, just need to bump the bower.json version before the release.  Otherwise, the bower.json in the .tgz will be different and give a little warning in the bower install:

screen shot 2015-02-10 at 9 30 48 am

Should still be good though.

**Comment by gaearon** [comment]
Thank you! I'm sorry I forgot about it and only realized post factum :-(

**Comment by gaearon** [comment]
@jgable 0.8 is out

**Comment by jgable** [comment]
Everything is auto updating now on bower, as long as the bower.json version
is updated there won't be anything else you have to do.

**Comment by gaearon** [comment]
Oh, that's sweet! How does it work?

**Comment by jgable** [comment]
It matches the bower.json version with the github tags and downloads the .tgz files from Github directly; no need to publish them.  If you have bower installed you can check it out by running `bower info react-dnd`.

**Pull request merged**
