### PR TITLE
Handlers for touch backend

### PR DESCRIPTION
**Pull request by itrelease**

### CODE REVIEW

**Comment by nelix** [comment]
This is looking good, I will look at it more closely after we finish of the current refactoring

**Comment by gaearon** [comment]
We're going to revisit this after #111 is done. Closing for now, as it's built against the old API we're aiming to replace.

**Comment by itshallrun** [comment]
we will look at it more closely...
image


maybe in 2020 ? :D

**Comment by aggregate1166877** [comment]
Hi @nelix and @gaearon, are there still plans to review and merge this in?

**Pull request closed without merging**
