### PR TITLE
Dustbin simple ES5 example

### PR DESCRIPTION
**Pull request by vkbansal**
Simple Dustbin example inES5 for issue #200

### CODE REVIEW

**Comment by gaearon** [comment]
Thanks! How do you run this? (e.g. to verify it works)

**Comment by vkbansal** [comment]
I didn't verify as I wanted to close the discussion asap. But I'll do it later today and update the PR.

**Comment by gaearon** [comment]
Much appreciated!

**Comment by vkbansal** [comment]
Moved to https://github.com/vkbansal/react-dnd-es5-examples

**Pull request closed without merging**
