### PR TITLE
Add bower support

### PR DESCRIPTION
**Pull request by jgable**
Adds a bower.json with info from the package.json.  Leaves the dist, dist-modules and modules folders for supporting global, commonjs, and amd consumers.

### CODE REVIEW

**Comment by gaearon** [comment]
How do I maintain this? Just increment a version number?
Why use Bower over NPM?

**Comment by jgable** [comment]
Yes, just incrementing the version number should be fine as you publish.  You'll also need to [`bower register`](http://bower.io/docs/creating-packages/#register) it so it can be installed by name. 

> Why use Bower over NPM?

That's a good question, one that I'm sure the rest of the internet has a lot to say about better than I could.  In my current project we are setup to use Bower, and a lot of other components also support it.

If you'd rather not support it, I'm happy to fork and publish it myself.  If you ping me via an @jgable when a new version is published I'll also bump the bower fork.

**Comment by gaearon** [comment]
I added you to collaborators, please feel free to bump it! I'll be pinging you on releases.

**Comment by gaearon** [comment]
@jgable 0.6.4 is out

**Pull request merged**
