### PR TITLE
Add nested example

### PR DESCRIPTION
**Pull request by nelix**
This is exactly the same as #85 by @itrelease
I just trimmed a commit so that its just the nested example.

### CODE REVIEW

**Comment by nelix** [comment]
@gaearon thoughts?

**Comment by gaearon** [comment]
@nelix I'm sorry for dragging feet on this. I remember about it every single day but it's been very rough few days since we just launched after a year of private beta and there was a lot of last-minute fiddling and bugfixing. Give me please a few days to wrap it up and I'll get back to you!

**Comment by gaearon** [comment]
Superseded by https://github.com/gaearon/react-dnd/pull/90

**Comment by gaearon** [comment]
Pardon, I meant by #98.

**Pull request closed without merging**
