### PR TITLE
Fix memory leak when rendering on the server

### PR DESCRIPTION
**Pull request by gaearon**
This attempts to address #337 without changing the public API.
It *almost* works but:

* I don’t know whether it actually fixes the memory leak—I would appreciate somebody testing this
* Setting drag preview in `componentDidMount()` is currently broken (e.g. `Drag Layer Custom` example)

I’m not sure how much trouble it is to fix (2) but I would appreciate at least a confirmation that the approach solves the initial problem.

The important part here is that we unsubscribe completely as soon as we have the information needed for the initial render, but we later subscribe again in `componentDidMount()` by explicitly calling `receiveProps()` which calls into the subscription code in `receiveType()`.

cc @longlho

### CODE REVIEW

**Comment by gaearon** [comment]
Regarding (2), the fix as I imagine it would be to create a `HandlerConnector` class with `receiveHandlerId()` instead of the current `bindConnectorMethods()` helper. The `HandlerConnector` would work similarly to `bindConnectorMethods()` but would also keep a reference to the latest `node` and `options` and make sure to pass them to the backend even if the handler ID has changed, and the handler is reconnected to backend.

**Comment by gaearon** [comment]
I updated the pull request so that all examples work correctly.
Please let me know whether this fixes the memory leak.
If it does, I’ll merge and release.

**Comment by gaearon** [comment]
I decided to merge this in. It doesn’t seem to introduce any bugs, is more correct, and as a bonus improves performance in some common cases.

**Comment by gaearon** [comment]
Please give v2.1.1 a try.

**Comment by longlho** [comment]
yup will do :) tks for the fix!

**Pull request merged**
