### PR TITLE
Implement mousemove backend

### PR DESCRIPTION
**Pull request by gaearon**
This is the first stab at an alternative backend. When we get this to a properly working state, implementing touch support (#16) will be a piece of cake.

- [x] Get item displaying while dragging in http://localhost:8080/drag-around-experimental
- [x] Get item dropping and changing position after drop in http://localhost:8080/drag-around-experimental 
- [x] Implement droppable (enter, leave, over)
- [x] Add barebone Touch backend
- [ ] Add a mousemove backend example for Dustbin and Sortable, add snapping to mousemove Drag Around
- [ ] Prevent text selection
- [ ] Make sure nested drop targets and drag sources work without a problem, just like with HTML5 backend
- [ ] Decide if we can infer (or allow injectable) mouse cursors for different `DropEffects`
- [ ] Figure out a way to set specific backends for components and have them exist on page without conflicts. Forbid operations on one backend if another backend is active. Components with different backends shouldn't notice each other. Think this through
- [ ] Make sure mouse is resilient against corner cases
- [ ] Make sure coordinates are calculated correctly regardless of scrolling position
- [ ] Implement Touch backend
- [ ] Internal refactoring (if needed)
- [ ] Update documentation

Huge thanks to @nelix for getting this ball rolling.

### CODE REVIEW

**Comment by gaearon** [comment]
@nelix 

I made some progress, try `MouseDragDropMixin` and (quite broken) `TouchDragDropMixin`—both on container and item. `MouseDragDropMixin` should work OK now, although corner cases may be broken. `TouchDragDropMixin` only works for moving item and is horribly slow.

**Comment by gaearon** [comment]
The useful part of this has already been extracted into 0.9 refactoring, and the rest will be superseded by future work on top of #111 so I'm closing this.

**Comment by gavinwahl** [comment]
@gaearon Is there a mousemove backend now? I can't find documentation anywhere?

**Comment by an5rag** [comment]
This seems promising: https://github.com/zyzo/react-dnd-mouse-backend

**Pull request closed without merging**
