### PR TITLE
Kanban example

### PR DESCRIPTION
**Pull request by nelix**
Only thing not yet working is empty column drag

### CODE REVIEW

**Comment by gaearon** [comment]
Let's hold this off until #69.

**Comment by nelix** [comment]
I was just placing it here for inspiration and discussion about requirements

**Comment by nelix** [comment]
@Martindelataille I'll get this updated pretty soon

**Comment by Martindelataille** [comment]
@nelix @gaearon Thx for your amazing work

**Comment by gaearon** [comment]
@nelix Let me know if you'd like to update it for the 1.0 API!

**Comment by gaearon** [comment]
Closing as outdated. If you came here interested in a Kanban example, check out https://github.com/survivejs/webpack_react/tree/master/project_source/08_building_kanban/kanban_app by @bebraw!

**Comment by electricSemyon** [comment]
@gaearon I`ve got 404 on this link.

**Comment by bebraw** [comment]
@electricSemyon The current demo is [here](https://github.com/survivejs-demos/redux-demo). You can also find versions for MobX, Cerebral, and Alt below the organization.

**Comment by electricSemyon** [comment]
@bebraw Oh, thank you!

**Pull request closed without merging**
